sources:
  - Sources/AblyAssetTrackingSubscriber/WorkerQueue/SubscriberWorkerQueueProperties.swift
templates:
  - Sourcery/templates/AutoMockable.stencil
output:
  Tests/SubscriberTests/Mocks/GeneratedMocks.swift
args:
  autoMockableTestableImports:
    - AblyAssetTrackingSubscriber
  autoMockableImports:
    - AblyAssetTrackingInternal
