sources:
  - Sources/AblyAssetTrackingSubscriber/SubscriberDelegate.swift
  - Sources/AblyAssetTrackingSubscriber/Subscriber.swift
templates:
  - Sourcery/templates/AutoMockable.stencil
output:
  Tests/Support/AblyAssetTrackingSubscriberTesting/Mocks/GeneratedMocks.swift
args:
  autoMockableImports:
    - AblyAssetTrackingSubscriber
