sources:
  - Sources/AblyAssetTrackingInternal/AblyWrapper/SDK/AblySDKProtocols.swift
  - Sources/AblyAssetTrackingInternal/AblyWrapper/AblySubscriber.swift
templates:
  - Sourcery/templates/AutoMockable.stencil
output:
  Tests/Support/AblyAssetTrackingInternalTesting/Mocks/GeneratedMocks.swift
args:
  autoMockableImports:
    - AblyAssetTrackingCore
    - AblyAssetTrackingInternal
    - Ably
