disabled_rules:
  - force_try
  - todo

opt_in_rules:
  - empty_count

excluded:
  - Pods

force_try:
  severity: warning

line_length:
  warning: 250
  ignores_comments: true

file_length:
  warning: 700
  error: 1200