only_rules:
  - empty_parameters
  - vertical_whitespace
  - trailing_whitespace
  - comment_spacing
  - anyobject_protocol # See https://forums.swift.org/t/class-only-protocols-class-vs-anyobject/11507/10 for details.
