disabled_rules:
  # Rules we’re currently violating:
  - cyclomatic_complexity
  - function_body_length
  - generic_type_name
  - large_tuple
  - nesting
  - type_body_length
  - type_name
  # Rules we’re currently violating even though we’ve opted in to them in opt_in_rules:
  - missing_docs
  - todo
  - xct_specific_matcher
  # Rules we’re currently violating even though we’ve added configuration for them:
  - file_header
  - file_length
  - identifier_name
  - line_length

opt_in_rules:
  - anonymous_argument_in_multiline_closure
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - fallthrough
  - fatal_error_message
  - file_header
  - missing_docs
  - override_in_extension
  - vertical_whitespace_closing_braces
  - xct_specific_matcher
  - yoda_condition
  - todo
  - shorthand_optional_binding
  - pattern_matching_keywords
  - multiline_literal_brackets
  - vertical_parameter_alignment_on_call
  - multiline_parameters
  - multiline_parameters_brackets
  - multiline_arguments
  - multiline_arguments_brackets
  - trailing_newline
  - unneeded_parentheses_in_closure_argument

excluded:
  - "**/.build"
  - .git
  - "**/GeneratedMocks.swift"

file_header:
  forbidden_string: //

line_length:
  warning: 250
  ignores_comments: true

file_length:
  warning: 700
  error: 1200

identifier_name:
  excluded: 'id'
