disabled_rules:
  - colon
  - comma
  - control_statement

opt_in_rules:
  - empty_count

excluded:
  - Pods

force_try:
  severity: warning

line_length:
  warning: 250
  ignore_comments: true

file_length:
  warning: 700
  error: 1200