disabled_rules:
  # All of the default rules of type "metrics". We have no reason to believe that the arbitrary defaults picked by SwiftLint are helpful.
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - function_parameter_count
  - large_tuple
  - line_length
  - nesting
  - type_body_length
  # Rules we’re currently violating:
  - generic_type_name
  - type_name
  # Rules we’re currently violating even though we’ve opted in to them in opt_in_rules:
  - missing_docs
  - todo
  - xct_specific_matcher
  # Rules we’re currently violating even though we’ve added configuration for them:
  - file_header
  - identifier_name

opt_in_rules:
  - anonymous_argument_in_multiline_closure
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - fallthrough
  - fatal_error_message
  - file_header
  - missing_docs
  - override_in_extension
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - xct_specific_matcher
  - yoda_condition
  - todo
  - shorthand_optional_binding
  - pattern_matching_keywords
  - multiline_literal_brackets
  - vertical_parameter_alignment_on_call
  - multiline_parameters
  - multiline_parameters_brackets
  - multiline_arguments
  - multiline_arguments_brackets
  - trailing_newline
  - unneeded_parentheses_in_closure_argument
  - multiline_function_chains
  - implicit_return

excluded:
  - "**/.build"
  - .git
  - "**/GeneratedMocks.swift"

file_header:
  forbidden_string: //

identifier_name:
  excluded: 'id'
