on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Select Specific Xcode Version
        run: |
          sudo xcode-select -s /Applications/Xcode_14.2.app
          echo "Selected Xcode version:"
          xcodebuild -version
          
      - name: Configure MapBox Secret Token for Download
        run: |
          echo "machine api.mapbox.com" >> ~/.netrc
          echo "login mapbox" >> ~/.netrc
          echo "password $MAPBOX_DOWNLOADS_TOKEN" >> ~/.netrc
        env:
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}

      - name: Run All Tests
        run: ./Scripts/test.sh
        env:
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}

      - name: Xcodebuild Logs Artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: xcodebuild-logs
          path: test-results/xcodebuild-logs/Logs

      - name: Upload test results
        if: always()
        uses: ably/test-observability-action@v1
        with:
          server-auth: ${{ secrets.TEST_OBSERVABILITY_SERVER_AUTH_KEY }}
          path: 'test-results/junit'

  check-log-parser:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run LogParser tests
        run: swift test
        working-directory: Tools/Library/LogParser

      - name: Build LogParserExample app
        run: swift build
        working-directory: Tools/Library/LogParserExample
