on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure MapBox Secret Token for Download
        run: |
          echo "machine api.mapbox.com" >> ~/.netrc
          echo "login mapbox" >> ~/.netrc
          echo "password $MAPBOX_DOWNLOADS_TOKEN" >> ~/.netrc
        env:
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}

      - name: Run All Tests using Fastlane
        run: |
          bundle install
          fastlane test_all
        env:
          MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
      
      - name: Xcodebuild Logs Artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: xcodebuild-logs
          path: |
            ~/Library/Developer/Xcode/DerivedData/*/Logs/Test
