on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: macos-latest
    env:
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure MapBox Secret Token for Download
        run: |
          echo "machine api.mapbox.com" >> ~/.netrc
          echo "login mapbox" >> ~/.netrc
          echo "password $MAPBOX_DOWNLOADS_TOKEN" >> ~/.netrc
        env:
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}

      - name: Install bundle
        run: |
          bundle install

      - name: Execute all tests using Fastlane
        run: |
          bundle exec fastlane test_all

      - name: Ensure Pod Install Works
        run: |
          bundle exec pod install

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-core
          path: coverage_core/

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-subscriber
          path: coverage_subscriber/

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-publisher
          path: coverage_publisher/
