on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure MapBox Secret Token for Download
        run: |
          echo "machine api.mapbox.com" >> ~/.netrc
          echo "login mapbox" >> ~/.netrc
          echo "password $MAPBOX_DOWNLOADS_TOKEN" >> ~/.netrc
        env:
          MAPBOX_DOWNLOADS_TOKEN: sk.eyJ1IjoibC1zenlzemtvd3NraSIsImEiOiJja3ZiMHNhbzAzZWU4MnJscDFoaDZvMmJlIn0.gRYKod9Ha8UygjGLF7Ty3g

      - name: Run All Tests
        run: ./Scripts/./test.sh
        env:
          MAPBOX_ACCESS_TOKEN: pk.eyJ1IjoibC1zenlzemtvd3NraSIsImEiOiJja3ZiMHN5cXowOWFkMnNwbnI0cDcxbmJoIn0.mLwe9TnrUpYPY0bt9GoOuQ
          ABLY_API_KEY: ${{ secrets.ABLY_API_KEY }}

      - name: Xcodebuild Logs Artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: xcodebuild-logs
          path: ~/Library/Developer/Xcode/DerivedData/*/Logs
