on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v2

      - name: Select Specific Xcode Version
        run: |
          sudo xcode-select -s /Applications/Xcode_13.2.app
          echo "Selected Xcode version:"
          xcodebuild -version

      # https://github.com/jpsim/SourceKitten#installation
      - name: Install SourceKitten via Homebrew
        run: brew install sourcekitten

      - name: Configure MapBox Secret Token for Download
        run: |
          echo "machine api.mapbox.com" >> ~/.netrc
          echo "login mapbox" >> ~/.netrc
          echo "password $MAPBOX_DOWNLOADS_TOKEN" >> ~/.netrc
        env:
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}

      - name: Build Documentation
        run: |
          bundle install
          ./jazzy/build.sh
          ls -al docs

      - uses: ably/sdk-upload-action@v1
        with:
          sourcePath: docs
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactName: jazzy
