on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure MapBox Secret Token for Download
        run: |
          echo "machine api.mapbox.com" >> ~/.netrc
          echo "login mapbox" >> ~/.netrc
          echo "password $MAPBOX_DOWNLOADS_TOKEN" >> ~/.netrc
        env:
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}

      - name: Run All Tests using Fastlane
        run: |
          gem install fastlane
          fastlane test_all
